language: java
jdk:
  - openjdk8

# Travis CI 를 어느 브랜치가 푸시될 때 수행할지 지정.
branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# master 브랜치에 푸시되었을 때 수행. 프로젝트 내부에 둔 gradlew 을 통해 clean & build 수행
script: "./gradlew clean build"

before_deploy:
  - zip -r Lets-boot *
  - mkdir -p deploy
  - mv Lets-boot.zip deploy/Lets-boot.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: lets-boot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: lets-boot-build
    key: Lets-boot.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip # 압축 확장자 지정
    application: Lets-boot
    deployment_group: Lets-boot-group
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - jyonglee95@gmail.com

# gradlew 실행 권한 부여
before_install:
  - chmod +x gradlew