version: 0.0 # codedeploy version
os: linux
files:
  - source: / # codedeploy 로부터 온 모든 파일을 destination 으로 이동
    destination: /home/ec2-user/app/step3/zip/ # 파일 받을 위치 386p. 무중단 배포를 위해 step3 로 위치 변경
    overwrite: yes # 기존 파일 덮어쓸지 옵션 설정 - yes 이므로 덮어씀

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: stop.sh # 엔진엑스와 연결되어 있지 않은 스프링 부트를 종료한다.
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: start.sh # 엔진엑스와 연결되어 있지 않은 Port로 새 버전의 스프링 부트를 시작합니다.
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: health.sh # 새 스프링 부트가 정상적으로 실행됐는지 확인
      timeout: 60
      runas: ec2-user
